### ISSUE TITLE
imputation on GPU

### ISSUE THREAD

**Issue by asheetal** [cran/ECLRMC#1]
I see notes that this imputation can be done on GPU. II am trying to run this code

>library(ECLRMC)
>library(gpuR)
>x = matrix(c(5.1, 4.9, NA, 4.6, 3.5, 3.0, 3.2, 3.1, 1.4, NA, 1.3, 1.5), byrow = TRUE, ncol=4)
>gpux = gpuMatrix(x, type="double")
>ECLRMC(gpux, beta = 0.2)

And I get the error

>Error in xfill[xnas] <- 0 : object of type 'S4' is not subsettable
>In addition: Warning message:
>In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'

Can anyone comment on the correct way of using ECLRMC on GPU?

**Comment by gaborcsardi** [comment]
For the record, this is a read only mirror of CRAN, see the `DESCRIPTION` file for the package authors and potentially URLs. Thanks!
